# Generated by Django 6.0.3 on 2026-04-21 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverPhone', models.CharField(max_length=15)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('totalAmount', models.FloatField()),
                ('shippingAddress', models.TextField()),
                ('paymentMethod', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItemId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('book', models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.PROTECT, to='books.book')),
                ('order', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
                'managed': True,
            },
        ),
    ]
