# Generated by Django 6.0.3 on 2026-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=5)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
    ]
