# Generated by Django 6.0.3 on 2026-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('awards', models.TextField(blank=True, null=True)),
                ('bookFormat', models.CharField(blank=True, max_length=50, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
                ('coverImg', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('publishDate', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('setting', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
