# Generated by Django 5.2 on 2025-05-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
